name: Deploy to Self-Hosted Runner

on:
  push:
    branches:
      - main2

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_CLOUDFLARE_SITE_KEY="${{ secrets.NEXT_PUBLIC_CLOUDFLARE_SITE_KEY }}" \
            --build-arg NEXT_PUBLIC_CLOUDFLARE_SECRET_KEY="${{ secrets.NEXT_PUBLIC_CLOUDFLARE_SECRET_KEY }}" \
            -t dnholding-landing:latest .

      - name: Stop and Remove Old Container
        run: |
          docker stop dnholding-landing || true
          docker rm dnholding-landing || true

      - name: Run New Container
        run: |
          docker run -d \
            --name dnholding-landing \
            --restart unless-stopped \
            -p 3000:3000 \
            -e NEXT_PUBLIC_CLOUDFLARE_SITE_KEY="${{ secrets.NEXT_PUBLIC_CLOUDFLARE_SITE_KEY }}" \
            -e NEXT_PUBLIC_CLOUDFLARE_SECRET_KEY="${{ secrets.NEXT_PUBLIC_CLOUDFLARE_SECRET_KEY }}" \
            dnholding-landing:latest

      - name: Clean up unused Docker images
        run: |
          docker image prune -f
